add_newline = true
command_timeout = 1000

format = "$directory$git_branch$git_status$package$nodejs$python$rust$golang$cmd_duration$line_break$character"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "bold cyan"
read_only = " ro"
read_only_style = "red"

[git_branch]
symbol = "git "
style = "bold purple"

[git_status]
style = "yellow"
format = "([$all_status$ahead_behind]($style) )"

[package]
disabled = false
style = "208"

[nodejs]
format = "([node $version](bold green) )"

[python]
format = "([py $version](bold yellow) )"

[rust]
format = "([rs $version](bold red) )"

[golang]
format = "([go $version](bold cyan) )"

[cmd_duration]
min_time = 500
format = "([took $duration](dimmed white) )"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold blue)"
